pipeline {
    agent any

    parameters {
        string(name: 'NAMESPACE', defaultValue: 'hadoop1', description: 'Namespace for Hadoop cluster')
        string(name: 'REPLICAS', defaultValue: '2', description: 'Number of DataNode and NodeManager replicas')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the Hadoop-deploy git repository
                checkout scm
            }
        }

        stage('Prepare Environment') {
            steps {
                dir('Hadoop-deploy') {
                    sh 'chmod +x deploy.sh'
                }
            }
        }

        stage('Deploy Hadoop via Ansible') {
            steps {
                dir('Hadoop-deploy') {
                    withEnv(["NAMESPACE=${params.NAMESPACE}", "REPLICAS=${params.REPLICAS}"]) {
                        sh './deploy.sh'
                    }
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                dir('Hadoop-deploy') {
                    sh '''
                        export PATH=$PWD/bin:$PATH
                        if [ -f "../configs/config" ]; then
                          export KUBECONFIG="$PWD/../configs/config"
                        fi
                        kubectl get pods -n ${NAMESPACE}
                        kubectl get svc -n ${NAMESPACE}
                    '''
                }
            }
        }
    }
}
